services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    networks:
      - es-net
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  elasticsearch:
    container_name: es-container
    image: elasticsearch:8.7.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    image: kibana:8.7.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - es-net
    ports:
      - 6379:6379
  app:
    container_name: AAAPASSPORTS
    #image: 'base_final'
    build:
        context: .
        dockerfile: Dockerfile
    networks:
      - es-net
    ports:
      - 5000:80
    environment:
      - ConnectionStrings:postgresPassports=User ID=root;Password=root;Server=db;Port=5432;Database=passports
      - ConnectionStrings:redisPassports=redis:6379
networks:
  es-net:
    driver: bridge    