// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Passports.Data;

#nullable disable

namespace Passports.Migrations
{
    [DbContext(typeof(PassportContext))]
    partial class PassportContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Passports.Models.Passport", b =>
                {
                    b.Property<short>("Series")
                        .HasColumnType("smallint");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ChangeDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActual")
                        .HasColumnType("boolean");

                    b.HasKey("Series", "Number");

                    b.HasIndex("IsActual");

                    b.ToTable("Passports");
                });
#pragma warning restore 612, 618
        }
    }
}
